config/routes.rb
#     destroy_admin_session DELETE /admins/sign_out(.:format)                                                               admins/sessions#destroy
#        new_admin_password GET    /admins/password/new(.:format)                                                           admins/passwords#new
#       edit_admin_password GET    /admins/password/edit(.:format)                                                          admins/passwords#edit
#            admin_password PATCH  /admins/password(.:format)                                                               admins/passwords#update
#                           PUT    /admins/password(.:format)                                                               admins/passwords#update
#                           POST   /admins/password(.:format)                                                               admins/passwords#create
# cancel_admin_registration GET    /admins/cancel(.:format)                                                                 admins/registrations#cancel
#    new_admin_registration GET    /admins/sign_up(.:format)                                                                admins/registrations#new
#   edit_admin_registration GET    /admins/edit(.:format)                                                                   admins/registrations#edit
#        admin_registration PATCH  /admins(.:format)                                                                        admins/registrations#update
#                           PUT    /admins(.:format)                                                                        admins/registrations#update
#                           DELETE /admins(.:format)                                                                        admins/registrations#destroy
#                           POST   /admins(.:format)                                                                        admins/registrations#create
#                  products GET    /products(.:format)                                                                      products#index
#                           POST   /products(.:format)                                                                      products#create
#               new_product GET    /products/new(.:format)                                                                  products#new
#              edit_product GET    /products/:id/edit(.:format)                                                             products#edit
#                   product GET    /products/:id(.:format)                                                                  products#show
#                           PATCH  /products/:id(.:format)                                                                  products#update
#                           PUT    /products/:id(.:format)                                                                  products#update
#                           DELETE /products/:id(.:format)                                                                  products#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#                     carts POST   /carts(.:format)                                                                         carts#create
#                      cart GET    /carts/:id(.:format)                                                                     carts#show
#                           PATCH  /carts/:id(.:format)                                                                     carts#update
#                           PUT    /carts/:id(.:format)                                                                     carts#update
#                           DELETE /carts/:id(.:format)                                                                     carts#destroy
#                  payments GET    /payments(.:format)                                                                      payments#index
#                           POST   /payments(.:format)                                                                      payments#create
#               new_payment GET    /payments/new(.:format)                                                                  payments#new
#                   payment GET    /payments/:id(.:format)                                                                  payments#show
#                           PATCH  /payments/:id(.:format)                                                                  payments#update
#                           PUT    /payments/:id(.:format)                                                                  payments#update
#           admins_products GET    /admins/products(.:format)                                                               admins/products#index
#                           POST   /admins/products(.:format)                                                               admins/products#create
#        new_admins_product GET    /admins/products/new(.:format)                                                           admins/products#new
#       edit_admins_product GET    /admins/products/:id/edit(.:format)                                                      admins/products#edit
#            admins_product GET    /admins/products/:id(.:format)                                                           admins/products#show
#                           PATCH  /admins/products/:id(.:format)                                                           admins/products#update
#                           PUT    /admins/products/:id(.:format)                                                           admins/products#update
#                           DELETE /admins/products/:id(.:format)                                                           admins/products#destroy
#              admins_users GET    /admins/users(.:format)                                                                  admins/users#index
#          edit_admins_user GET    /admins/users/:id/edit(.:format)                                                         admins/users#edit
#               admins_user GET    /admins/users/:id(.:format)                                                              admins/users#show
#                           PATCH  /admins/users/:id(.:format)                                                              admins/users#update
#                           PUT    /admins/users/:id(.:format)                                                              admins/users#update
#                           DELETE /admins/users/:id(.:format)                                                              admins/users#destroy
#           admins_payments GET    /admins/payments(.:format)                                                               admins/payments#index
#            admins_payment PATCH  /admins/payments/:id(.:format)                                                           admins/payments#update
#                           PUT    /admins/payments/:id(.:format)                                                           admins/payments#update
#                refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do

root 'products#index'

devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}

devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
}

resources :products, only: [:index, :show]
resources :users, only: [:index, :show, :edit, :update, :destroy]
get "/users/:id/carts" => "users#cart", as: "user_cart"
resources :carts, only: [:create, :destroy, :update]
resources :payments, only: [:new, :index, :create, :show, :update]

match '/finish', to: 'payments#finish', via: 'get'

namespace :admins do
  resources :products, only: [:index, :show, :edit, :new, :create, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :payments, only: [:index, :show, :edit, :update, :destroy]
  resources :artist, only: [:index, :create, :destroy]
  resources :label, only: [:index, :create, :destroy]
  resources :genre, only: [:index, :create, :destroy]

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :payment_method
  has_many :purchase_products, dependent: :destroy
  accepts_nested_attributes_for :purchase_products, allow_destroy: true
  has_one :address, through: :users

  validates :shipping_last_name, presence: true
  validates :shipping_first_name, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
end

app/controllers/admins/payments_controller.rb
class Admins::PaymentsController < ApplicationController

	before_action :authenticate_admin!

  layout "admin"

  def index
  	@users = User.all

    # (params[:q])に検索パラメーターが入り、Productテーブルを検索する@qオブジェクトを生成
    @search_user = User.ransack(params[:q])
    # 検索結果を表示
    @results_user = @search_user.result.page(params[:page]).reverse_order.per(20)
  end

  def show
    @payment = Payment.find(params[:id])
    @purchase_products = @payment.purchase_products
  end

  def edit
  	@payment = Payment.find(params[:id])
    @purchase_products = @payment.purchase_products
  end

  def update
    @payment = Payment.find(params[:id])
    if @payment.update(payment_params)
    flash[:success] = '変更内容が保存されました。'
    redirect_to admins_payments_path
    else
      render :edit
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:danger] = '購入履歴が削除されました。'
    redirect_to admins_payments_path
  end

private
  def payment_params
  	params.require(:payment).permit(:user_id, :payment_method_id, :shipping_last_name, :shipping_first_name, :shipping_postal_code, :shipping_address, :order_status, purchase_products_attributes: [:id, :quantity, :price])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

	before_action :authenticate_user!

  def new
    @payment = Payment.new
    @address = current_user.addresses.first
    @payment.user_id = current_user.id
    @carts = current_user.carts
    @total_price = 0
    @carts.each do |cart|
      @total_price += (cart.product.price * 1.08).floor * cart.quantity
    end
    @purchase_product = @payment.purchase_products.build
  end

  def create
    # @payment_method = PaymentMethod.find(params[:payment_method_id])
    # @payment.payment_method_id = @payment_method.id

    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id

    if @payment.save
      @payment.user.carts.each do |cart|
        purchase_product = PurchaseProduct.new
        purchase_product.product_id = cart.product.id
        purchase_product.quantity = cart.quantity
        purchase_product.price = (cart.product.price * 1.08).floor
        purchase_product.payment_id = @payment.id
        purchase_product.save

        purchase_product.product.stock = purchase_product.product.stock - purchase_product.quantity
        purchase_product.product.save

      end
      @payment.user.carts.destroy_all
      redirect_to finish_path
    else
      @payment.user_id = current_user.id
      @address = current_user.addresses.first
      @carts = current_user.carts
      @total_price = 0
      @carts.each do |cart|
        @total_price += (cart.product.price * 1.08).floor * cart.quantity
      end
      @purchase_product = @payment.purchase_products.build
      render :new
    end
  end

  def index
    @payments = current_user.payments.page(params[:page]).reverse_order
  end

  def show
    @payment = Payment.find(params[:id])
    @purchase_products = @payment.purchase_products
  end




  def finish
  end

private
  def payment_params
  	params.require(:payment).permit(
      :user,
      :payment_method_id,
      :shipping_last_name,
      :shipping_first_name,
      :shipping_postal_code,
      :shipping_address,
      :order_status,
      purchase_products_attributes: [:id, :quantity, :price, :payment_id]
      )
  end


end

app/helpers/admins/payments_helper.rb
module Admins::PaymentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/finish.html.erb

<p class="text-center h3">購入が完了しました。<br>商品発送までしばらくお待ちください。</p>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-4 col-md-offset-1">

        <%= link_to "商品一覧へ戻る" , products_path, class: "btn btn-lg btn-primary pull-right" %>
      </div>
        <div class="col-md-4 col-md-offset-2">
          <%= link_to "購入履歴を見る", payments_path, class: "btn btn-lg btn-primary" %>
        </div>
    </div>
  </div>
</div>

app/views/payments/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">

    <div class="row">
      <div class="col-md-5">
        <h1>購入履歴一覧</h1>
        <p>現在の送料 500円</p>
      </div>
    </div>

    <table class="table table-bordered">
      <tr>
        <th>購入日</th>
        <th>送付先氏名</th>
        <th>送付先郵便番号</th>
        <th>送付先住所</th>
        <th>ステータス</th>
        <th>支払方法</th>
        <th>総計（送料込み）</th>
      </tr>


      <% @payments.each do |payment| %>
          <tr>
            <td><%= payment.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= payment.shipping_last_name %>　<%= payment.shipping_first_name %></td>
            <td><%= payment.shipping_postal_code %></td>
            <td><%= payment.shipping_address %></td>
            <td><%= payment.order_status %></td>
            <td><%= payment.payment_method.payment_method %></td>
            <td><% sum = 0 %>
              <% payment.purchase_products.each do |purchase_product| %>
              <% sum += purchase_product.price * purchase_product.quantity %>
                <% end %>
                <%= sum + 500 %>円
            </td>
            <td><%= link_to "詳細", payment_path(payment.id), class: "col-xs-12 btn btn-info" %></td>
          </tr>
      <% end %>
    </table>

    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-4"></div>
        <div class="col-md-4">
        <%= link_to "マイページへ", user_path(current_user), class: "btn btn-primary btn-lg center-block btn-block" %>
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-4">
        </div>
        <div class="col-md-5">
          <%= paginate @payments, class: "paginate" %>
        </div>
        <div class="col-md-3">
        </div>
      </div>

    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>購入手続き</h1>

<div id="error_explanation">
  <% if @payment.errors.any? %>
    <ul>
      <% @payment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

    <div class="col-md-10 col-md-offset-1">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>シングル/アルバム名</th>
            <th>アーティスト名</th>
            <th>購入枚数</th>
            <th>価格(税込)</th>
          </tr>
        </thead>
        <tbody>
          <% @carts.each do |cart| %>
            <tr>
              <td><%= cart.product.title %></td>
              <td><%= cart.product.artist.artist %></td>
              <td><%= cart.quantity %>枚</td>
              <td>￥<%= (cart.product.price * 1.08).floor %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>


  <div class="row border"> <!-- cssでborder設定する -->
    <div class="col-md-10 col-md-offset-1">

      <p>
        <label>
          お届け先をご確認ください。登録されている宛先と異なる場合は入力してください。
        </label>
      </p>
  <%= form_for (@payment) do |f| %>
          <p>
            <label for="name">お届け先氏名：</label>
            <%= f.text_field :shipping_last_name, value: current_user.last_name, class: "form-control" %>
            <%= f.text_field :shipping_first_name, value: current_user.first_name, class: "form-control" %>
          </p>
          <p>
            <label for="postal_code">郵便番号：</label>
            <%= f.text_field :shipping_postal_code, value: @address.postal_code, class: "form-control" %>
          </p>
          <p>
            <label for="postal_code">お届け先住所：</label>
            <%= f.text_field :shipping_address, value: @address.address,class: "form-control" %>
          </p>
    </div>
  </div>
  <div class="row border"> <!-- cssでborder設定する -->
    <div class="col-md-10 col-md-offset-1">
        <h4>支払方法を選択</h4>
          <label>
            <%= f.radio_button :payment_method_id, "1" %>銀行振り込み
          </label><br>
          <label>
            <%= f.radio_button :payment_method_id, "2" %>クレジットカード
          </label><br>
          <label>
            <%= f.radio_button :payment_method_id, "3" %>代引
          </label>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-md-offset-1 h3">商品小計｜¥ <%= @total_price %> </div>
    <div class="col-md-3 h3">送料｜¥ 500</div>
    <div class="col-md-3 h3">総計（税込）｜¥ <%= @total_price + 500 %> </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="col-md-3 col-md-offset-8">
        <%= f.submit "購入", class: "btn btn-primary btn-lg center-block btn-block" %>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
  <% end %>
</div>

app/views/payments/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">

    <div class="row">
      <div class="col-md-5">
        <h1>購入履歴詳細</h1>
        <p>現在の送料 500円</p>
      </div>
    </div>

    <table class="table table-bordered">
      <tr>
        <th>購入内容</th>
        <th>購入枚数</th>
        <th>価格（税込）</th>
      </tr>


        <% @purchase_products.each do |purchase_product| %>
        <% if purchase_product.product == nil %>
              <td></td>
              <td><%= purchase_product.quantity %>枚</td>
              <td><%= purchase_product.price %>円</td>
          <% else %>
            <tr>
              <td><%= purchase_product.product.title %></td>
              <td><%= purchase_product.quantity %>枚</td>
              <td><%= purchase_product.price %>円</td>
            </tr>
          <% end %>
        <% end %>
    </table>
    </div>

  <div class="row">
    <div class="col-md-12">
      <div class="col-md-4"></div>
      <div class="col-md-4">
      <%= link_to "戻る", payments_path, class: "btn btn-primary btn-lg center-block btn-block" %>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
  </div>
</div>